myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shopaccount/', include('shopaccount.urls')),
]

shopaccount/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('create_view/<data>', views.create_view, name='create_view'),
    path('list_view/', views.list_view, name='list_view'),
    path('detail_view/<id>/<data>', views.detail_view, name='detail_view'),
    path('update_view/<id>/<data>', views.update_view, name='update_view'),
    # path('delete_item/<id>', views.delete_item, name='delete_item'),    

    # API data
    path('list_marketplace/', views.list_marketplace, name='list_marketplace'),
    path('list_products/', views.list_products, name='list_products'),
    path('list_transaction/<start_date>/<end_date>', views.list_transaction, name='list_transaction'),
    path('list_detail/<id>/<data>/<start_date>/<end_date>', views.list_detail, name='list_detail'),
    path('list_payout_type/', views.list_payout_type, name='list_payout_type'),
    path('list_payout/', views.list_payout, name='list_payout')
] 

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shopaccount/models.py
from django.db import models

class Marketplace(models.Model):
    mp_name = models.CharField(max_length=200)

    def __str__(self):
        return self.mp_name

class Transaction(models.Model):
    date = models.DateField('date created')
    mp_id =  models.ForeignKey(Marketplace, to_field='id', on_delete=models.CASCADE)
    order_id = models.CharField(max_length=200)
    product_name = models.CharField(max_length=200)
    product_category = models.CharField(max_length=200)
    product_article = models.CharField(max_length=200)
    quantity = models.IntegerField(default=0)
    selling_price = models.DecimalField(max_digits=12, decimal_places=2)
    basic_price = models.DecimalField(max_digits=12, decimal_places=2)
    notes = models.TextField(max_length=500)
    
    def __date(self):
        return self.date

    def __mp_id(self):
        return self.mp_id

    def __order_id(self):
        return self.order_id

    def __product_name(self):
        return self.product_name

    def __product_category(self):
        return self.product_category

    def __product_article(self):
        return self.product_article

    def __quantity(self):
        return self.quantity

    def __selling_price(self):
        return self.selling_price

    def __basic_price(self):
        return self.basic_price

    def __notes(self):
        return self.notes

    def profit(self):
        return round(self.selling_price - (self.basic_price * self.quantity),2)
    
    def margin(self):
        profit = self.selling_price - (self.basic_price * self.quantity)
        return round((profit / self.selling_price) * 100,2)

class PayoutType(models.Model):
    pay_type_name = models.CharField(max_length=200)
    pay_type_perc = models.FloatField()

    def __pay_type_name(self):
        return self.pay_type_name

    def __pay_type_perc(self):
        return self.pay_type_perc

class Payout(models.Model):
    pay_date = models.DateField('date created')
    pay_name = models.CharField(max_length=200)
    pay_type_id = models.ForeignKey(PayoutType, to_field='id', on_delete=models.CASCADE)
    pay_value = models.DecimalField(max_digits=12, decimal_places=2)

    def __pay_date(self):
        return self.pay_date

    def __pay_name(self):
        return self.pay_name

    def __pay_type_id(self):
        return self.pay_type_id

    def __pay_value(self):
        return self.pay_value

shopaccount/forms.py
from django import forms
from .models import Marketplace, Transaction, PayoutType, Payout
from django.conf import settings
 
# creating a form
class MarketplaceForm(forms.ModelForm):
 
    # create meta class
    class Meta:
        # specify model to be used
        model = Marketplace
 
        # specify fields to be used
        fields = [
            "mp_name",
        ]

class TransactionForm(forms.ModelForm):
 
    # create meta class
    class Meta:
        # specify model to be used
        model = Transaction
 
        # specify fields to be used
        fields = [
            "date",
            "mp_id",
            "order_id",
            "product_name",
            "product_category",
            "product_article",
            "quantity",
            "selling_price",
            "basic_price",
            "notes"
        ]

class PayoutTypeForm(forms.ModelForm):
 
    # create meta class
    class Meta:
        # specify model to be used
        model = PayoutType
 
        # specify fields to be used
        fields = [
            "pay_type_name", "pay_type_perc"
        ]

class PayoutForm(forms.ModelForm):
 
    # create meta class
    class Meta:
        # specify model to be used
        model = Payout
 
        # specify fields to be used
        fields = [
            "pay_date", "pay_name", "pay_type_id", "pay_value"
        ]

shopaccount/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.http import HttpResponse, JsonResponse
from django.conf import settings
from django.views.generic import ListView
from django.core.paginator import Paginator
from django.db.models import Q, Count
from filter_and_pagination import FilterPagination
from .models import Marketplace, Transaction, PayoutType, Payout
from .forms import MarketplaceForm, TransactionForm, PayoutTypeForm, PayoutForm
from .serializers import TransactionSerializer, MarketplaceSerializer, PayoutTypeSerializer, PayoutSerializer, ProductSerializer

def create_view(request, data):
    # dictionary for initial data with
    # field names as keys
    context ={}; data_mp = {}; data_pt = {}
 
    if data == '1':
        # add the dictionary during initialization
        form = MarketplaceForm(request.POST or None)
    elif data == '2':
        data_mp = Marketplace.objects.all()
        form = TransactionForm(request.POST or None) 
    elif data == '3':
        form = PayoutTypeForm(request.POST or None)
    else:
        data_pt = PayoutType.objects.all()
        form = PayoutForm(request.POST or None)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(settings.BASE_LINK+"/list_view")

         
    context['form'] = form
    resultset = {
        'dataset': data,
        'data_mp': data_mp,
        'data_pt': data_pt,
        'context': context
    }

    return render(request, "create_view.html", resultset)

def list_view(request):
    url = settings.BASE_LINK
    return render(request, "list_view.html", {'url':url})

def detail_view(request, id, data):
    context = {}
    if (data == '1'):
        context = Marketplace.objects.get(id = id)

    return render(request, "detail_view.html", {'data_id':id, 'data_no': data, 'marketplace': context})

def list_marketplace(request):
    queryset = Marketplace.objects.all()
    context  = MarketplaceSerializer(queryset, many=True).data
    resultset = {'dataset':context}

    return JsonResponse(resultset, safe=False)

def list_transaction(request, start_date, end_date):
    # dictionary for initial data with
    # field names as keys
    # add the dictionary during initialization
    queryset = Transaction.objects.all().order_by('date')
    if (start_date!='-' and end_date!='-'):
        queryset = Transaction.objects.filter(date__range=[start_date, end_date]).order_by('-date')

    context = TransactionSerializer(queryset, many=True).data      
    resultset = {'dataset': context}

    return JsonResponse(resultset, safe=False)

def list_products(request):
    # dictionary for initial data with
    # field names as keys
    # add the dictionary during initialization
    queryset = Transaction.objects.all().values('product_article').distinct().annotate(total_sales_by_product=Count('product_article')).order_by('-total_sales_by_product')

    context = ProductSerializer(queryset, many=True).data      
    resultset = {'dataset': context}

    return JsonResponse(resultset, safe=False)

def list_detail(request, id, data, start_date, end_date):
    # dictionary for initial data with
    # field names as keys
    context = {}; data_list = {}
    _basic_price = 0; _total_profit = 0; _total_qty = 0; _total_selling_price = 0; _total_basic_price = 0
    _total_payout = 0
    mp = ""; tr = ""; pt = ""; p = ""

    
    if data=='1':
        # add the dictionary during initialization
        context = Marketplace.objects.get(id = id)
        data_list['dataset'] = Transaction.objects.filter(mp_id = context.id).order_by('-date')
        if (start_date!='-' and end_date!='-'):
            data_list['dataset'] = Transaction.objects.filter(mp_id = context.id, date__range=[start_date, end_date]).order_by('-date')
        #_total_qty = Transaction.objects.aggregate(Sum('quantity'))['quantity__sum']
        #_total_selling_price = Transaction.objects.aggregate(Sum('selling_price'))['selling_price__sum']
        #_total_basic_price = Transaction.objects.aggregate(Sum('basic_price'))['basic_price__sum']
        
        mp = MarketplaceSerializer(context, many=False).data
        tr = TransactionSerializer(data_list['dataset'], many=True).data 

        for _data_list in data_list['dataset']:
            _total_qty += _data_list.quantity
            _total_selling_price += _data_list.selling_price
            _total_basic_price += _data_list.basic_price
            _basic_price = _data_list.quantity * _data_list.basic_price
            _total_profit += _data_list.selling_price - _basic_price
    elif data == '2':
        context = Transaction.objects.get(id = id)
        tr = TransactionSerializer(context, many=False).data
    else:
        # add the dictionary during initialization
        context = PayoutType.objects.get(id = id)
        data_list['dataset'] = Payout.objects.filter(pay_type_id = context.id).order_by('-pay_date')
        if (start_date!='-' and end_date!='-'):
            data_list['dataset'] = Payout.objects.filter(pay_type_id = context.id, pay_date__range=[start_date, end_date]).order_by('-pay_date')

        for _data_list in data_list['dataset']:
            _total_payout += _data_list.pay_value   
        
        pt = PayoutTypeSerializer(context, many=False).data
        p = PayoutSerializer(data_list['dataset'], many=True).data 
    
    resultset = {
                    'marketplace': mp, 
                    'transaction': tr, 
                    'payout_type': pt,
                    'payout': p,
                    'total_payout': _total_payout,
                    'total_profit':_total_profit, 
                    'total_qty':_total_qty,
                    'total_selling_price':_total_selling_price,
                    'total_basic_price':_total_basic_price
                }

    return JsonResponse(resultset, safe=False)

def list_payout_type(request):
    queryset = PayoutType.objects.all()
    context  = PayoutTypeSerializer(queryset, many=True).data
    resultset = {'dataset':context}

    return JsonResponse(resultset, safe=False)

def list_payout(request):
    queryset = Payout.objects.all()
    context  = PayoutSerializer(queryset, many=True).data
    resultset = {'dataset':context}

    return JsonResponse(resultset, safe=False)

# update view for details
def update_view(request, id, data):
    # dictionary for initial data with
    # field names as keys
    context = {}; data_mp = {}; data_mp_id = {}; data_trx = {}; 
    data_pt = {}; data_pt_id = {}; data_p = {}
    date_format = settings.DATE_INPUT_FORMATS
 
    if data == '1':
        # fetch the object related to passed id
        # obj = get_object_or_404(Marketplace, id = id)
        data_mp_id = Marketplace.objects.get(id = id)
     
        # pass the object as instance in form
        form = MarketplaceForm(request.POST or None, instance = data_mp_id)
    elif data == '2':
        # fetch the object related to passed id
        data_mp = Marketplace.objects.all()
        data_trx = Transaction.objects.get(id = id)
     
        # pass the object as instance in form
        form = TransactionForm(request.POST or None, instance = data_trx)
    elif data == '3':
        data_pt_id = PayoutType.objects.get(id = id)
        # pass the object as instance in form
        form = PayoutTypeForm(request.POST or None, instance = data_pt_id)
    else:
        data_pt = PayoutType.objects.all()
        data_p = Payout.objects.get(id = id)
        form = PayoutForm(request.POST or None, instance = data_p)

    # save the data from the form and
    # redirect to detail_view
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(settings.BASE_LINK+"/list_view")
 
    # add form dictionary to context
    context["form"] = form
    resultset = {
                    'dataset':data, 
                    'data_trx': data_trx, 
                    'data_mp': data_mp, 
                    'data_mp_id': data_mp_id,
                    'data_pt_id': data_pt_id,
                    'data_pt': data_pt,
                    'data_p': data_p,
                    'formset':context
                }

    return render(request, "update_view.html", resultset)

# def delete_item(request, id):
#     # fetch the object related to passed id
#     obj = get_object_or_404(Marketplace, id = id)
 
#     if request.method =="POST":
#         # delete object
#         obj.delete()
#         return HttpResponseRedirect("../list_view")
 
#     return render(request, "list_view.html", {'delete_mp_item': True, 'item_id': id})

# def filtering(request):
#     queryset = FilterPagination.filter_and_pagination(request, Transaction)
#     serialize_data = TransactionSerializer(queryset['queryset'], many=True).data
      
#     resultset = {'dataset': serialize_data, 'pagination': queryset['pagination']}

#     return JsonResponse(resultset, safe=False)

shopaccount/templates/create_view.html
{% extends 'header.html' %}

{% block title %} Create {% endblock %}

{% block content %}
    <form method="POST" enctype="multipart/form-data" class="frm_input">
        <!-- Security token -->
        {% csrf_token %}
     
        <!-- Using the formset -->
        <!-- {{ form.as_p }} -->
        {% if dataset == '1' %}
            <!-- {{ formset.form.as_p }} -->
        <table>
            <tr>   
                <td>
                    <label for="id_mp_name">Marketplace name:</label>
                </td>
                <td>
                    <input type="text" name="mp_name" maxlength="200" required="" id="id_mp_name">
                </td>
            </tr>
        </table>
        {% elif dataset == '2' %}
        <table>
            <tr>
                <td>
                    <label for="id_date">Date created:</label>
                </td>
                <td>
                    <input type="date" name="date" class="datepicker" required="" id="id_date">
                </td>
            </tr>
            <tr>
                <td>
                    <label for="id_mp_id">Select marketplace:</label>
                </td>
                <td>
                    <select name="mp_id" required="" id="id_mp_id">
                        <option value="" selected>-select-</option>
                        {% for data in data_mp %}
                            <option value="{{ data.id }}">{{ data.mp_name }}</option>
                        {% endfor %}
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    <label for="id_order_id">Order id:</label>
                </td>
                <td>
                    <input type="text" name="order_id" maxlength="200" required="" id="id_order_id">
                </td>
            </tr>
            <tr>
                <td>
                    <label for="id_product_name">Product name:</label>
                </td>
                <td>
                    <input type="text" name="product_name" maxlength="200" required="" id="id_product_name">
                </td>
            </tr>
            <tr>
                <td>
                    <label for="id_product_category">Product category:</label>
                </td>
                <td>
                    <input type="text" name="product_category" maxlength="200" required="" id="id_product_category">
                </td>
            </tr>
            <tr>
                <td>
                    <label for="id_product_category">Product article:</label>
                </td>
                <td>
                    <input type="text" name="product_article" maxlength="200" required="" id="id_product_article">
                </td>
            </tr>
            <tr>
                <td>
                    <label for="id_quantity">Quantity:</label>
                </td>
                <td>
                    <input type="number" name="quantity" required="" id="id_quantity">
                </td>
            </tr>
            <tr>
                <td>
                    <label for="id_selling_price">Selling price:</label>
                </td>
                <td>    
                    <input type="number" name="selling_price" step="0.01" required="" id="id_selling_price">                    
                </td>
            </tr>
            <tr>
                <td>
                    <label for="id_basic_price">Basic price:</label>
                </td>
                <td>
                    <input type="number" name="basic_price" step="0.01" required="" id="id_basic_price">
                </td>
            </tr>
            <tr>
                <td> 
                    <label for="id_notes">Notes:</label>
                </td>
                <td>
                    <textarea name="notes" cols="40" rows="10" maxlength="500" required="" id="id_notes" style="width: 298px; height: 146px;"></textarea>
                </td>
            </tr>
        </table>
        {% elif dataset == '3' %}
        <table>
            <tr>   
                <td>
                    <label for="id_pay_type_name">Category:</label>
                </td>
                <td>
                    <input type="text" name="pay_type_name" maxlength="200" required="" id="id_pay_type_name">
                </td>
            </tr>
            <tr>   
                <td>
                    <label for="id_pay_type_name">Percentage:</label>
                </td>
                <td>
                    <input type="text" name="pay_type_perc" maxlength="200" required="" id="id_pay_type_perc">
                </td>
            </tr>
        </table>
        {% else %}
        <table>
            <tr>
                <td>
                    <label for="id_date">Date created:</label>
                </td>
                <td>
                    <input type="date" name="pay_date" class="datepicker" required="" id="id_pay_date">
                </td>
            </tr>
            <tr>
                <td>
                    <label for="id_order_id">Payout Name:</label>
                </td>
                <td>
                    <input type="text" name="pay_name" maxlength="200" required="" id="id_pay_name">
                </td>
            </tr>
            <tr>
                <td>
                    <label for="id_pay_type_id">Select Pay Type:</label>
                </td>
                <td>
                    <select name="pay_type_id" required="" id="id_pay_type_id">
                        <option value="" selected>-select-</option>
                        {% for data in data_pt %}
                            <option value="{{ data.id }}">{{ data.pay_type_name }}</option>
                        {% endfor %}
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    <label for="id_pay_value">Payout Value:</label>
                </td>
                <td>
                    <input type="number" name="pay_value" step="0.01" required="" id="id_pay_value">
                </td>
            </tr>
        </table>
        {% endif %}
        <div class="text-center">
            <input type="submit" value="Create" class="btn_submit">
            <input type="reset" class="btn_reset">
        </div>
    </form>
{% endblock %}

shopaccount/templates/detail_view.html
{% extends 'header.html' %}

{% block title %} 
    {% if data_no == '1' %}
        Detail : {{ marketplace.mp_name }}
    {% else %}
        Detail Transaction
    {% endif %}
{% endblock %}

{% block content %}
    <input type="hidden" id="data_id" value="{{ data_id }}">
    <input type="hidden" id="data_no" value="{{ data_no }}">
    {% if data_no == '1' %} 
    <table id="table-detail-mp" class="table">
        <tr>
            <td>ID</td>
            <td class="mp_id"></td>
        </tr>
        <tr>
            <td>Marketplace name</td>
            <td class="mp_name"></td>  
        </tr>
        <tr>
            <td>Total Quantitiy of Order</td>
            <td class="total_qty_order"></td>
        </tr>
        <tr>
            <td>Total Selling Price</td>
            <td class="total_selling_price"></td>
        </tr>
        <tr>
            <td>Total Basic Price</td>
            <td class="total_basic_price"></td>
        </tr>
        <tr>
            <td>Total Profit</td>
            <td class="total_profit"></td>
        </tr>
    </table>
    <hr>
    <div class="text-center">
        <form method="GET" onsubmit="event.preventDefault(); filter_by_date('tr-detail')">
            <label>Search from</label>
            <input type="date" name="" id="date_from">
            <label>to</label>
            <input type="date" name="" id="date_to">
            <input type="submit" name="" id="btn_search_by_date">
            <input type="reset" name="">
        </form>
    </div>
    <hr>
    <table id="table-detail-tr" class="table">
        <!-- set in jquery -->
    </table>
    {% elif data_no == '2' %}
    <table class="table">
        <tr>
            <td>ID</td>
            <td class="tr_id"></td>
        </tr>
        <tr>
            <td>Marketplace</td>
            <td class="tr_mp_id"></td>
        </tr>
        <tr>
            <td>Order ID</td>
            <td class="order_id"></td>
        </tr>
        <tr>
            <td>Product name</td>
            <td class="product_name"></td>
        </tr>
        <tr>
            <td>Product Category</td>
            <td class="product_category"></td>
        </tr>
        <tr>
            <td>Product Article</td>
            <td class="product_article"></td>
        </tr>
        <tr>
            <td>Order Qty</td>
            <td class="quantity"></td>
        </tr>
        <tr>
            <td>Nett Selling Price</td>
            <td class="selling_price"></td>
        </tr>
        <tr>
            <td>Basic Price</td>
            <td class="basic_price"></td>
        </tr>
        <tr>
            <td>Profit</td>
            <td class="profit"></td>
        </tr>
        <tr>
            <td>Notes</td>
            <td class="notes"></td>
        </tr>
    </table>
    {% else %}
    <table id="table-detail-pt" class="table">
        <tr>
            <td>ID</td>
            <td class="pay_type_id"></td>
        </tr>
        <tr>
            <td>Payout Type</td>
            <td class="pay_type_name"></td>  
        </tr>
        <tr>
            <td>Payout Perc</td>
            <td class="pay_type_perc"></td>
        </tr>
        <tr>
            <td>Total Payout</td>
            <td class="total_payout"></td>
        </tr>
    </table>
    <hr>
    <div class="text-center">
        <form method="GET" onsubmit="event.preventDefault(); filter_by_date('p-detail')">
            <label>Search from</label>
            <input type="date" name="" id="pay_date_from">
            <label>to</label>
            <input type="date" name="" id="pay_date_to">
            <input type="submit" name="" id="btn_search_pay_date">
            <input type="reset" name="">
        </form>
    </div>
    <hr>
    <table id="table-detail-p" class="table">
        <!-- set in jquery -->
    </table>
    {% endif %}
{% endblock %}

shopaccount/templates/update_view.html
{% extends 'header.html' %}

{% block title %} Update {% endblock %}

{% block content %}
    <!-- Create a Form -->
    <form method="POST" class="frm_input">
        <!-- Security token by Django -->
        {% csrf_token %}

        {% if dataset == '1' %}
            <!-- {{ formset.form.as_p }} -->
        <table>
            <tr>   
                <td>
                    <label for="id_mp_name">Marketplace name:</label>
                </td>
                <td>
                    <input type="text" name="mp_name" maxlength="200" required="" id="id_mp_name" value="{{ data_mp_id.mp_name }}">
                </td>
            </tr>
        </table>
        {% elif dataset == '2' %}
        <table>
            <tr>
                <td>
                    <label for="id_date">Date created:</label>
                </td>
                <td>
                    <input type="date" name="date" class="datepicker" required="" id="id_date" value="{{ data_trx.date|date:'Y-m-d' }}">
                </td>
            </tr>
            <tr>
                <td>
                    <label for="id_mp_id">Select marketplace:</label>
                </td>
                <td>
                    <select name="mp_id" required="" id="id_mp_id">
                        <option value="">-select-</option>
                        {% for data in data_mp %}
                            <option value="{{ data.id }}" {% if data.id == data_trx.mp_id.id %} selected {% endif %}>{{ data.mp_name }}</option>
                        {% endfor %}
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    <label for="id_order_id">Order id:</label>
                </td>
                <td>
                    <input type="text" name="order_id" maxlength="200" required="" id="id_order_id" value="{{ data_trx.order_id}}">
                </td>
            </tr>
            <tr>
                <td>
                    <label for="id_product_name">Product name:</label>
                </td>
                <td>
                    <input type="text" name="product_name" maxlength="200" required="" id="id_product_name" value="{{ data_trx.product_name}}">
                </td>
            </tr>
            <tr>
                <td>
                    <label for="id_product_category">Product category:</label>
                </td>
                <td>
                    <input type="text" name="product_category" maxlength="200" required="" id="id_product_category" value="{{ data_trx.product_category}}">
                </td>
            </tr>
            <tr>
                <td>
                    <label for="id_product_category">Product article:</label>
                </td>
                <td>
                    <input type="text" name="product_article" maxlength="200" required="" id="id_product_article" value="{{ data_trx.product_article}}">
                </td>
            </tr>
            <tr>
                <td>
                    <label for="id_quantity">Quantity:</label>
                </td>
                <td>
                    <input type="number" name="quantity" required="" id="id_quantity" value="{{ data_trx.quantity }}">
                </td>
            </tr>
            <tr>
                <td>
                    <label for="id_selling_price">Selling price:</label>
                </td>
                <td>    
                    <input type="number" name="selling_price" step="0.01" required="" id="id_selling_price" value="{{ data_trx.selling_price }}">                    
                </td>
            </tr>
            <tr>
                <td>
                    <label for="id_basic_price">Basic price:</label>
                </td>
                <td>
                    <input type="number" name="basic_price" step="0.01" required="" id="id_basic_price" value="{{ data_trx.basic_price }}">
                </td>
            </tr>
            <tr>
                <td> 
                    <label for="id_notes">Notes:</label>
                </td>
                <td>
                    <textarea name="notes" cols="40" rows="10" maxlength="500" required="" id="id_notes" style="width: 298px; height: 146px;">{{ data_trx.notes }}</textarea>
                </td>
            </tr>
        </table>
        {% elif dataset == '3' %}
        <table>
            <tr>   
                <td>
                    <label for="id_pay_type_name">Category:</label>
                </td>
                <td>
                    <input type="text" name="pay_type_name" maxlength="200" required="" id="id_pay_type_name" value="{{ data_pt_id.pay_type_name}}">
                </td>
            </tr>
            <tr>   
                <td>
                    <label for="id_pay_type_name">Percentage:</label>
                </td>
                <td>
                    <input type="text" name="pay_type_perc" maxlength="200" required="" id="id_pay_type_perc" value="{{ data_pt_id.pay_type_perc }}">
                </td>
            </tr>
        </table>
        {% else %}
        <table>
            <tr>
                <td>
                    <label for="id_date">Date created:</label>
                </td>
                <td>
                    <input type="date" name="pay_date" class="datepicker" required="" id="id_pay_date" value="{{ data_p.pay_date|date:'Y-m-d' }}">
                </td>
            </tr>
            <tr>
                <td>
                    <label for="id_order_id">Payout Name:</label>
                </td>
                <td>
                    <input type="text" name="pay_name" maxlength="200" required="" id="id_pay_name" value="{{ data_p.pay_name }}">
                </td>
            </tr>
            <tr>
                <td>
                    <label for="id_pay_type_id">Select Pay Type:</label>
                </td>
                <td>
                    <select name="pay_type_id" required="" id="id_pay_type_id">
                        <option value="" selected>-select-</option>
                        {% for data in data_pt %}
                            <option value="{{ data.id }}" {% if data.id == data_p.pay_type_id.id %} selected {% endif %}>{{ data.pay_type_name }}</option>
                        {% endfor %}
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    <label for="id_pay_value">Payout Value:</label>
                </td>
                <td>
                    <input type="number" name="pay_value" step="0.01" required="" id="id_pay_value" value="{{ data_p.pay_value}}">
                </td>
            </tr>
        </table>
        {% endif %}
        <div class="text-center">
            <input type="submit" value="Update" class="btn_submit">
            <input type="reset" class="btn_reset">
        </div>
    </form>
{% endblock %}